### ISSUE TITLE
Improve search engine

### ISSUE THREAD

**Issue by thomashardy** [maur1th/naxos#45]
It'd be cool to be able to search for posts inside the whole threads and not only in the topic's titles.

:o

**Comment by maur1th** [comment]
I'll have good news on that matter soon enough :)

**Comment by thomashardy** [comment]
Oh yeah!

**Comment by thomashardy** [comment]
Another thing that could be improved is how the search engine managed the letters with accents.
E.g. the search _impots_ vs _impôts_ does not return the same results. Maybe it would be great not to take account of accents?

**Comment by thomashardy** [comment]
Hey! Something new regarding this ticket, oh admin, my dear admin?

**Comment by maur1th** [comment]
as far as I know this is done, feel free to open another ticket if not
