### ISSUE TITLE
Smilies which are sharing the same part of code

### ISSUE THREAD

**Issue by thomashardy** [maur1th/naxos#55]
Another smilies issues!

If two smilies shares the same part of code, e.g. `:o` and `:oh:` the longest one is not well displayed, as the shortest one has the priority.

See: http://i.imgur.com/N3Iqsv0.png

**Comment by thomashardy** [comment]
It's working now!

**Comment by maur1th** [comment]
Fixed by https://github.com/maur1th/naxos/commit/145c2f597033b1fefdbd2f1954a923b435809fda
