### ISSUE TITLE
Error 500 when changing avatar

### ISSUE THREAD

**Issue by thomashardy** [maur1th/naxos#63]
The FoRuM members are encountering a 500 error when trying to upload a new avatar.

**Steps to reproduce:**
- Go to https://forumdomain.tld/user/
- Click on the button to choose a new file (“Choisir un fichier” on the French version of Chrome)
- Select your image and validate
- Click on the blue button “Enregistrer” at the bottom of the page to save your preferences

**Actual result:**

We got a 500 error
See screenshot: https://i.imgur.com/mFlCHr9.png
Sometimes, a user who tries to change his avatar gets it deleted, see topic `/forum/jep/equi-erreur-500-si-on-essaye-d-uploader-un-avatar/`

**Expected result:**

We should be able to change our avatar :o

Thanks!

**Comment by maur1th** [comment]
Done in: https://github.com/maur1th/naxos/commit/2bcaf185d0d62a2cb40e6a6cb369871137bcb0f2
